### ISSUE TITLE
Use terminology "Turso Platform API" for API tokens that are not database client tokens

### ISSUE THREAD

**Issue by CodingDoug** [tursodatabase/turso-cli#399]
We currently have three different types of tokens: database client auth tokens and user (CLI) auth tokens, and service auth tokens.  It's not very clear how they are different, and people have gotten confused about this in the past.  We should use consistent terminology between them, especially in the CLI where they are generated.

I've proposed that what we are currently calling the "Turso API" should clarified as the "Turso Platform API".  And the API used by client applications to query the database should be called the "Turso Client API".

This means that the help text for the CLI commands that manage service tokens (#323, #360) should be clear that these tokens are for use with the Turso Platform API, and not for use by application clients.  So, instead of calling them "API tokens" they should be called "Platform API tokens" consistently.  Ideally there is also a notice in help text for `api-tokens` that makes it clear that these are different than, and not interchangeable with, the client API tokens managed by `db tokens`.

Eventually we will probably also want to link to the CLI and platform API docs that discuss in more detail.

**Comment by notrab** [comment]
Closing this now as we have improved docs around the token types and the CLI has separate commands for creating db/group/api tokens.
