### ISSUE TITLE
Show database size in `db list`

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso-cli#40]
Show the database size as part of `db list`. Requires API work & integration with Fly.

**Comment by athoscouto** [comment]
This makes `db list` considerably slower, especially as databases grow bigger.
Even running `db list` against the local API with empty databases takes a few seconds.

https://github.com/chiselstrike/turso-cli/assets/7853668/c1e66846-b330-4d68-83a0-64429eb1f4ce

I'd revert it, at least in `db list`, until we have a faster way of getting database size.
WDYT? @penberg @haaawk

**Comment by haaawk** [comment]
This should improve the situation @athoscouto https://github.com/chiselstrike/turso-cli/pull/414
