### ISSUE TITLE
`account show` output is unclear

### ISSUE THREAD

**Issue by CodingDoug** [tursodatabase/turso-cli#496]
It's not clear what this command is supposed to do that's different than `org plan show`.  If it is supposed to be the same, consider removing this one and just have one canonical way of viewing current usage.

If this command is supposed to do something different, this needs to be made clear somehow.  The tabular output always looks the same based on the current org.

The output also seems incorrect for the current org in some cases.  If I am switched to a team org that's *not* on a billing plan, `org plan show` says "Active plan: starter", but `account show` says `You are currently on scaler plan.` If this output is supposed to always show data for the currently selected org, that feels like another reason that this command should probably not exist in favor of just `org plan show`.

**Comment by penberg** [comment]
I think we can just drop `turso account show` altogether or be explicit that it's an alias to `org plan show`.

**Comment by CodingDoug** [comment]
I doubt anyone will be strongly impacted if this command was removed entirely. But if we need something in place temporarily, an error message saying that it was replaced with another command should be fine.

**Comment by notrab** [comment]
Closing this since there is no longer a `turso account show` command.
