### ISSUE TITLE
Show some indicator of sqld version in `db show`

### ISSUE THREAD

**Issue by CodingDoug** [tursodatabase/turso-cli#576]
When running `turso db update`, there is no way of immediately know what changed, if anything changed at all.  One has to actually try to invoke new features or test bug fixes in order to find out that any desired change took place.

Also, when discussing bug reports or diagnosing problems, not knowing the version of sqld is active can be problematic.

It would help if there was some indicator of sqld version in the output of `db show`.  Ideally it should be linked to the open source tagged version of sqld. This helps external contributors can more easily understand what they should be working with if they want to duplicate issues locally, and also be able to find changelogs for the version they're working with.

**Comment by haaawk** [comment]
We've got version in db show now.
