### ISSUE TITLE
Add an alias `usage` for `inspect`

### ISSUE THREAD

**Issue by avinassh** [tursodatabase/turso-cli#577]
I find `db inspect` command to be confusing to get the usage info. By `inspect`, I would expect some internal technical info, not usage. 

I think we should add `db usage` as an alias for `db inspect` and phase out `inspect` in the future.

**Comment by premkirank** [comment]
@avinassh can you assign this to me? I would like to work on this

**Comment by avinassh** [comment]
@haaawk can you assign this issue @premkirank please, I don't have permissions to do so

**Comment by premkirank** [comment]
@avinassh Can I work on this as I have not been assigned yet?

**Comment by avinassh** [comment]
@premkirank yes, you can still work on it
