### ISSUE TITLE
Changing github username made me lose access to the database

### ISSUE THREAD

**Issue by iusedebian** [tursodatabase/turso-cli#628]
The database still exists and works, but I can't access it after logging in using github on another machine

turso db list
NAME     LOCATIONS     URL

**Comment by athoscouto** [comment]
Hi @iusedebian. Sorry for taking that long to get back to you.
If you do `turso org list` you should be able to see an organization with your old Github username.
Then you can do `turso org switch $OLD_USERNAME` to get to that org.
Then `turso db list` should work as expected.
After that, if you want to get back to your current org, just do `turso org switch iusedebian`.

**Comment by athoscouto** [comment]
If you hit any issues, please let us know on Discord.

**Comment by iusedebian** [comment]
> Hi @iusedebian. Sorry for taking that long to get back to you. If you do `turso org list` you should be able to see an organization with your old Github username. Then you can do `turso org switch $OLD_USERNAME` to get to that org. Then `turso db list` should work as expected. After that, if you want to get back to your current org, just do `turso org switch iusedebian`.

turso org list only displays my current username

NAME         SLUG                 
personal     iusedebian (current)

**Comment by athoscouto** [comment]
@iusedebian sorry about that! This required a special logic on our API. You should be able to see both orgs now. Let me know if that is not the case.

**Comment by iusedebian** [comment]
> @iusedebian sorry about that! This required a special logic on our API. You should be able to see both orgs now. Let me know if that is not the case.

oh my. Yes I can see both orgs now, thank you very much ❤️

**Comment by athoscouto** [comment]
I'll close this then. Feel free to reopen if needed.
