### ISSUE TITLE
Can't execute curl-based to install turso

### ISSUE THREAD

**Issue by kimdonginsu01** [tursodatabase/turso-cli#631]
Downloading Linux_x86_64 ...
######################################################################## 100.0%

Installing to /home/.turso

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

---------------------------------------------------
I'm using ubuntu 20.04 please help

**Comment by eriteric** [comment]
same here. I've tried the shell script, through pacman, and by downloading the tagged zip and manually installing - none work. `error: 'turso-cli-0.87.4.zip': invalid or corrupted package`

**Comment by notrab** [comment]
If this is still an issue please comment so I can re-open but I just tried on two other machines (one running Linux) and it seems to work fine.
