### ISSUE TITLE
need to wget callback url when logging in under a ssh connection

### ISSUE THREAD

**Issue by aifrim** [tursodatabase/turso-cli#634]
When you do `turso auth login` you have to visit an URL, complete login sequence, and then the the browser will be redirected to `http://localhost:PORT/?jwt=TOKEN&username=USERNAME`.

The problem is that sometimes I am using a SSH window to connect to a Linux server I have on my local network from my Windows laptop.

And every time I need to login I always have to

- Click on the link - ok
- Login on the web - ok
- Wait for browser to be redirected and 404 and then copy link
- Open another SSH connection to my Linux server
- Run `wget -O /dev/null http://localhost:PORT/?jwt=TOKEN&username=USERNAME` - so that the authentication process completes.

We can tell if we are under a SSH connection and change the authentication process from a callback URL to either HTTP long polling, or some else.

**Comment by haaawk** [comment]
There's a `--headless` flag in `turso auth login`:

```
╰──> turso auth login --headless 
Visit the following URL to login:
https://api.turso.tech?redirect=false
```

then you get a page with `ACCESS TOKEN`. Something like:
```
turso config set token "<token>"
```
Then you run that command in your ssh and you're logged in.

I'm gonna close this issue. Please reopen it @aifrim if that does not solve your problem.

**Comment by aifrim** [comment]
Should be fine now since it was introduced in https://github.com/tursodatabase/turso-cli/pull/791

**Comment by haaawk** [comment]
> Should be fine now since it was introduced in #791

It was introduced way earlier. #791 introduced it signup not login.

**Comment by aifrim** [comment]
Happy to hear that!
