### ISSUE TITLE
Use `libsql-server` instead of `sqld` for `turso dev`

### ISSUE THREAD

**Issue by CodingDoug** [tursodatabase/turso-cli#644]
The name of the binary is changing: https://github.com/libsql/sqld/pull/694

**Comment by CodingDoug** [comment]
In order to transition more cleanly. the CLI might want to try `libsql-server` first, then `sqld`.  If `sqld` is found, continue with a clear deprecation notice.

**Comment by notrab** [comment]
Closing this since `turso dev` will include this by default.
