### ISSUE TITLE
CLI in JS/Python + easier CI access

### ISSUE THREAD

**Issue by juliuslipp** [tursodatabase/turso-cli#651]
Hey guys,

I think with the recent upgrade to 500 on the free and 10000 DBs on the paid plan, it would make sense to also enable programmatic access to turso. Simple access token creation and integration into CI would also be a +.

Are there any solutions for this currently available or any plans to add this in the near futute?

**Comment by notrab** [comment]
Hey @juliuslipp, apologies for the late reply but we now have a [Platform API](https://docs.turso.tech/api-reference/introduction) that the CLI and Web App (Dashboard) uses. This API can be used to programmatically create databases, add remote replica locations, create API tokens, etc.

I'll go ahead and close this, as it looks resolved, but let me know if it needs to reopen <3
