### ISSUE TITLE
Can't create from file

### ISSUE THREAD

**Issue by mustafaakin** [tursodatabase/turso-cli#652]
I use  the following command:

```
turso db create --from-file data.db
```

It works suspiciously fast (200mb file, my upload is not that good). And I see the resulting database is empty. Then I try non-
existent file and it just creates a DB without giving an error.

```
turso db create --from-file postgres-is-nice-but-per-tenant-dbs-are-very-cool.db
```

**Comment by mustafaakin** [comment]
I think I found the suspected commit. It's parsed but does not seem to be used.

https://github.com/tursodatabase/turso-cli/commit/5156a4f0df79f044e1358a2d609eb89114d99a95#diff-917629523a8077e45f41d040eb8acf5b89ee38c85e64e1230137820cad24ddbcL173

**Comment by mustafaakin** [comment]
Okay the commit message makes it show like seed is not supported, which I think the files. OK; but beware that makes onboarding and testing stuff a bit harder.

**Comment by haaawk** [comment]
I think @athoscouto Just forgot to delete `addDbFromFileFlag` so that the option is not there at all.
