### ISSUE TITLE
Fresh cli install wrong version message

### ISSUE THREAD

**Issue by fecony** [tursodatabase/turso-cli#656]
Just after installing turso CLI with `brew install tursodatabase/tap/turso` command I got a message that newer version is available

> Friendly reminder that there's a newer version of Turso CLI available.
You're currently using version v0.85.1 while latest available version is v0.85.2.
Please consider updating to get new features and more stable experience. To update:

But when I tried to install it I saw weird behaviour
```bash
 richard  ~  turso update                                                                                                                         [23:41:55]
Current version: v0.85.1, latest version: v0.85.2
Warning: tursodatabase/tap/turso 0.85.2 already installed

 richard  ~  turso update                                                                                                                         [23:42:09]
Current version: v0.85.1, latest version: v0.85.2
Warning: tursodatabase/tap/turso 0.85.2 already installed

 richard  ~  turso version                                                                                                                        [23:42:17]
Error: unknown command "version" for "turso"
Run 'turso --help' for usage.

 ✘ richard  ~  turso --version                                                                                                                    [23:42:22]
turso version v0.85.1
```

No idea what version is really installed v0.85.1 or v0.85.2...

**Comment by haaawk** [comment]
What does `brew info turso` say?

**Comment by fecony** [comment]
> What does `brew info turso` say?

 richard  ~  brew info turso                                                                                                                      
==> tursodatabase/tap/turso: stable 0.85.2

https://github.com/tursodatabase/homebrew-tap
/usr/local/Cellar/turso/0.85.2 (6 files, 18.7MB) *
  Built from source on 2023-09-26 at 23:39:52
From: https://github.com/tursodatabase/homebrew-tap/blob/HEAD/turso.rb
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

 richard  ~  turso --version                                                                                                                      
turso version v0.85.1

**Comment by haaawk** [comment]
I can reproduce this. It's probably an issue with the versioning inside the binary but I will doublecheck. Here's what I got:
```
╰──> turso update
Current version: v0.84.1, latest version: v0.85.1
Running `brew update --auto-update`...

...

==> Upgrading 1 outdated package:
chiselstrike/tap/turso 0.84.1 -> 0.85.2

...

==> Upgrading chiselstrike/tap/turso
  0.84.1 -> 0.85.2 
  
  ...
  
  ╰──> turso --version
turso version v0.85.1
╭─[~/work/postgres-replication/replicator]
╰──> brew info turso
==> chiselstrike/tap/turso: stable 0.85.2
```

Notice how internal data about version is broken:
```
Current version: v0.84.1, latest version: v0.85.1
```
It thinks the lastest is 85.1 but brew has already 85.2

**Comment by haaawk** [comment]
Thanks for reporting @fecony

**Comment by haaawk** [comment]
This was an error in our release process.
`brew update & brew upgrade turso` fixes the problem and from now on `turso update` should work
