### ISSUE TITLE
SIGSEGV when checking for new updates

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso-cli#699]
Discord: https://discord.com/channels/933071162680958986/1165312200278282331

![image](https://github.com/tursodatabase/turso-cli/assets/81939/e37511cc-c8fa-4a5e-a96f-d0bb76c353ee)

**Comment by haaawk** [comment]
I believe this was fixed by https://github.com/tursodatabase/turso-cli/pull/747
@gris please make sure you close issues when you fix them :)
