### ISSUE TITLE
create volume failed with 400: {"error":"snapshot_retention must be at least 5"}

### ISSUE THREAD

**Issue by sandrinjoy** [tursodatabase/turso-cli#705]
I got this error when i used turso db create for the first time.
```
╰─ turso db create 
Error: could not create volume for app `turso-default-sandrinjoy`: error creating volume: create volume failed with 400: {"error":"snapshot_retention must be at least 5"}

create volume failed with 400: {"error":"snapshot_retention must be at least 5"}

create volume failed with 400: {"error":"snapshot_retention must be at least 5"}
```
but on the second time, it worked.

**Comment by athoscouto** [comment]
Sorry about it! This happened because of a temporary bug on our cloud provider.
You can see the [incident on our status page](https://status.turso.tech/incident/277137).
Shouldn't happen again though, so I'll close this issue.
