### ISSUE TITLE
Limits on payload size prevents taking db exports

### ISSUE THREAD

**Issue by jmcmullen** [tursodatabase/turso-cli#711]
```
turso db shell mighty-night .dump > my_db.sql
Error: failed to execute SQL: SELECT * FROM 'users'
Response is too large
```

This was previously reported here: https://github.com/libsql/sqld/issues/637

I would be happy to help contribute a fix for this under some guidance.

**Comment by athoscouto** [comment]
@jmcmullen what is the version of the CLI you're using? From [v0.87.0](https://github.com/tursodatabase/turso-cli/releases/tag/v0.87.0), that should not happen anymore.

**Comment by jmcmullen** [comment]
I was using an older version, can confirm this no longer occurs in the newer versions.
