### ISSUE TITLE
Turso GitHub action

### ISSUE THREAD

**Issue by frontsideair** [tursodatabase/turso-cli#727]
I looked for a GitHub action that installs Turso but couldn't find one.

It would be useful to create a new database branch when a PR is created and possibly clean up when it's merged; so I can safely do mutations and run migrations on preview deploys.

**Comment by armandabric** [comment]
I'm currently implementing manually this process with some custom action. Having an official one could be really helpful 👍

**Comment by notrab** [comment]
Hey @frontsideair @armandabric 

We'd certainly love to get something going here also more officially. We're all really excited by this idea.

Until we have one, would either of you be interested in co-authoring a blog post on how you have it setup manually? I'd love to feature you on the blog with this.

**Comment by notrab** [comment]
Hey @frontsideair @armandabric 

I published yesterday an [article](https://blog.turso.tech/create-a-database-branch-with-github-actions-07bbf804) on creating a database per branch with actions.

I also pushed this [GitHub Action](https://github.com/marketplace/actions/create-turso-database) so you don't have to set things up manually as described in the tutorial.

It's still early days but we'd love your feedback!

**Comment by notrab** [comment]
I'll go ahead and close this for now since there's an alpha version of the github action out. The article above should outline the `steps` required inside the action that you could extend to delete a database. I'm a bit more nervous to release a `delete-database` action though 🥵
