### ISSUE TITLE
[Feature Request] Is it possible to display latency information (ping)?

### ISSUE THREAD

**Issue by AdamUhh** [tursodatabase/turso-cli#763]
My personal production app uses Turso DB with the default location set to Paris (cdg), but I've noticed that API calls feel quite slow.
I'm wondering if cdg has the lowest latency for my region, or if there's a better location. 
It would be useful to have more details on pings and latency metrics when using something like `turso db locations`
Is something like this possible?

**Comment by notrab** [comment]
@AdamUhh do you need more than what you see when passing `--show-latencies`?

```bash
turso db locations --show-latencies
```
