### ISSUE TITLE
Pragmas are not in effect for whole of shell session?

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso-cli#784]
If the user executes a pragma statement such as `PRAGMA foreign_keys=OFF` in the shell, we need to make sure it's in effect for the whole of shell session. Right now, it seems like they are in effect only for a connection, but that's not enough because the shell doesn't keep the connection open.

**Comment by psarna** [comment]
Ref https://github.com/tursodatabase/libsql-shell-go/issues/163
