### ISSUE TITLE
Quickstart page opened as part of auto-update?

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso-cli#787]
We have a user point out that the Turso quickstart document page opens in the browser after few days of use. One thing I can think of is that our auto-update feature runs just `brew` and, therefore, runs the `turso quickstart` command. Let's verify to make sure autoupdate does not do this.

**Comment by SundayPowerEndre** [comment]
I just experienced this with brew and it felt very intrusive, would be really lovely if you could handle that somehow 🙏🏽

**Comment by penberg** [comment]
Hey @SundayPowerEndre, thanks for the confirmation! Yeah, it's not supposed to happen, will fix it.

**Comment by notrab** [comment]
This should now be resolved @SundayPowerEndre @penberg 🚀

**Comment by SundayPowerEndre** [comment]
Thank you so much guys, can confirm that it works as expected when i updated the tursodatabase/tap/turso via brew today 🥳
