### ISSUE TITLE
Can't Properly install turso in Windows 10

### ISSUE THREAD

**Issue by awencheww** [tursodatabase/turso-cli#788]
My PC:
![image](https://github.com/tursodatabase/turso-cli/assets/12206797/ce86f24c-9f63-4671-b4f4-3253f6128b4c)

installed wsl with Ubuntu

Tried to install via curl -sSfL https://get.tur.so/install.sh
Output: 
![image](https://github.com/tursodatabase/turso-cli/assets/12206797/9e2035cf-a384-4998-896b-3786e587da26)

Also tried to download install.sh manually and then try to install via wsl with Ubuntu installed
Output:
![image](https://github.com/tursodatabase/turso-cli/assets/12206797/041ff764-ce87-482d-a836-cc83f3935a7e)
![image](https://github.com/tursodatabase/turso-cli/assets/12206797/64cd8f7a-a5d1-49a5-8c6e-178978cd5674)

**Comment by AMDphreak** [comment]
The underlying Windows install gap is fixed by https://github.com/tursodatabase/turso-cli/pull/1058 and https://github.com/tursodatabase/turso-install/pull/19 (closes #318).
