### ISSUE TITLE
Architecture arm64 is not supported for libsql-server

### ISSUE THREAD

**Issue by artecoop** [tursodatabase/turso-cli#795]
Hello,
updating from v0.88.5 to v0.88.6 via `turso update`give me the following error

`Architecture arm64 is not supported for libsql-server`

macOS 14.3.1 on apple M1

**Comment by avinassh** [comment]
Hey! We fixed this issue recently: https://github.com/tursodatabase/turso-install/pull/13 

can you try again? If you had installed from the install script, then following should fix it: 

```
curl -sSfL https://get.tur.so/install.sh | bash
```
