### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by vhgn** [tursodatabase/turso-cli#797]
# Issue
Production database does not respond

**Comment by vhgn** [comment]
```
Error: failed to connect to database. err: failed to execute SQL: SELECT 1;
Post "https://***db***-**username**.turso.io/v2/pipeline": context deadline exceeded
```
I get this output in CLI

**Comment by vhgn** [comment]
This simple trick showed that I don't get a response back
```js
console.log("Got request")
const { rows } = await db.execute(`
	SELECT name
	FROM genres
`);
console.log("Got rows", rows);
```
It never outputted "Git rows..."

**Comment by gris** [comment]
@vhgn can you check it now?

**Comment by vhgn** [comment]
It worked! Thanks for the quick response.
Is there anything done wrong on my side?
How can I help preventing this happening in the future?

**Comment by gris** [comment]
no problem on your side, it was a network connectivity issue of our cloud provider, we have run an automation to fix all clusters that had this issue, but apparently the automation haven't catch all of them. Thanks for reporting

**Comment by vhgn** [comment]
Does having a starter plan versus a scaler plan have an impact?
