### ISSUE TITLE
turso-cli very high RAM usage during upload

### ISSUE THREAD

**Issue by kwmlodozeniec** [tursodatabase/turso-cli#826]
When creating database from a 3GB sqlite file turso was using over 11GB of RAM on my MacBook Pro M3
<img width="734" alt="image" src="https://github.com/tursodatabase/turso-cli/assets/1453791/1362a3af-f40e-4384-9199-f5b98334b3bc">

**Comment by avinassh** [comment]
Thanks for reporting! This is fixed now - https://github.com/tursodatabase/turso-cli/pull/827
