### ISSUE TITLE
"Wrong" recommended default location.

### ISSUE THREAD

**Issue by leandergangso** [tursodatabase/turso-cli#834]
I'm in Norway, so I would expect that either London or Frankfurt would be the best/fastest/closes option.

However when I run `turso db locations -l` I'm shown that `ewr` is the fastest(default).
Don't know why, but suspect something is not right here.  

![image](https://github.com/tursodatabase/turso-cli/assets/60340480/7ff0a7bc-7050-44cf-948b-180671a311fb)

FYI: I know for sure that the (default) location was `lhr(London)` some weeks back.

**Comment by notrab** [comment]
@leandergangso can you let me know what you see at https://region.turso.io? The lowest latency is selected by the CLI first, and it could be than London was having issues or slower to respond at the time.

**Comment by leandergangso** [comment]
Yhe, is London again. So most likely just some network issues, as you said.
