### ISSUE TITLE
"error code 502" when loading from dump with `turso db shell somedb < dump.sql`

### ISSUE THREAD

**Issue by kwerdna19** [tursodatabase/turso-cli#839]
Hello,

I have a relatively large dump file (about 240MB) and am having trouble executing it on my turso instance with the command `turso db shell somedb < dump.sql` as (mentioned in the docs [here](https://docs.turso.tech/cli/db/shell#load-from-dump))

The command connects for a second, and then outputs the entire dump file and at the bottom has what looks like a cut-off error message:

```
...
CREATE UNIQUE INDEX "List_name_key" ON "List"("name");
COMMIT;

error code 502:
andrew@Macbook Desktop %
```

Not sure Im running up against some limitations here but maybe seeing the full error message would help?  

Rather not post the dump here but let me know and I can try to make a generic repro.

Thanks!

**Comment by haaawk** [comment]
Hi @kwerdna19 Would you be willing to share the dump privately? Any reproducer would do really. Thanks

**Comment by taine-145** [comment]
Have the same issue, any solutions as of yet?

**Comment by nachaos** [comment]
same issue here

**Comment by haaawk** [comment]
I believe this is related to #735. While I'm fixing the other issue this one might get fixed as well. Will let you know once a new version of CLI with a fix is released.

In the meantime, @nachaos @taine-145 would you be willing to share the sql files that cause the issue for you? I can be here or privately to piotr@turso.tech

**Comment by taine-145** [comment]
Sure will pop you a mail

**Comment by haaawk** [comment]
> Sure will pop you a mail


Thanks @taine-145

**Comment by nachaos** [comment]
@haaawk I've jut sent the email, thanks for your help 💯

**Comment by haaawk** [comment]
turso cli v0.96.3 version has the improvements in that front

**Comment by nachaos** [comment]
Awesome @haaawk! Thank you for the quick response and taking care of this 💯

**Comment by haaawk** [comment]
You're welcome @nachaos. Let me know if you hit any other problems. If your dump is very big you might see some errors due to transaction taking too long but we will deal with it if you experience the problem.
