### ISSUE TITLE
unable to use turso cli without login

### ISSUE THREAD

**Issue by swanandx** [tursodatabase/turso-cli#866]
when I try to execute `turso dev`, it gives me following error:
```
You are not logged in, please login with turso auth login before running other commands
```

Users should be able to run `turso dev` without logging in! this was the existing behavior but i think got affected by #863 in latest release. ( edit: my bad, even v0.93.7, which is before this PR, has same bug, which means it's not affected by mentioned pr )

same is case with `help`, `relax` etc.!

turso version v0.93.8

**Comment by notrab** [comment]
This was resolved in a recent fix, thanks for reporting @swanandx
