### ISSUE TITLE
bad connection: failed to read JSON message: failed to read: read limited at 32769 bytes

### ISSUE THREAD

**Issue by xerosanyam** [tursodatabase/turso-cli#867]
unable to query data on cli

**Comment by irabinovitch** [comment]
seeing something similar when using the CLI for queries that turn more than a a couple hundred rows. it seems to have started after upgrading from v0.87.7 to v0.95.0 today.  

→  select count(*) from test;
COUNT(*) 
10391    

→  select * from test;
Error: driver: bad connection: failed to read JSON message: failed to read: read limited at 32769 bytes

→   select * from test limit 210;
<returned expected results>

→   select * from test limit 211;
Error: driver: bad connection: failed to read JSON message: failed to read: read limited at 32769 bytes

**Comment by MarinPostma** [comment]
This seems to be an issue with the websocket driver. a workaround is to use https instead:
`turso db shell https://<db-url>`

**Comment by athoscouto** [comment]
@xerosanyam @irabinovitch you should be able to go around this by doing `turso db shell https://$DB_HOST`.
So if your database URL is `libsql://my-db-athoscouto.turso.io`, do `turso db shell https://my-db-athoscouto.turso.io`.

**Comment by MarinPostma** [comment]
reopening until the patch hits this repo

**Comment by irabinovitch** [comment]
Confirming this has been resolved. Thank you.
