### ISSUE TITLE
Dump not working on version 0.96.5

### ISSUE THREAD

**Issue by ShuraimImran** [tursodatabase/turso-cli#906]
`turso db shell $DBNAME .dump > dump.sql` is not working on version 0.96.5. It creates an empty `dump.sql` file.

**Comment by dbryansmith** [comment]
@ShuraimImran did you find a fix for this? I am running into this issue.

**Comment by ShuraimImran** [comment]
@dbryansmith I did not. I took a dump from my co-worker's account and it worked so I moved on with that but I am still running into the issue from my account.
